- .travis.yml
> [Fix] travis file for first coverity scan test.

- README.md
> [Feat] Added coverity tag to README.md.

- config-files/ProviderMonitoringNetworkForeignBus.json
- docker-deploy/etc/ProviderMonitoringNetworkForeignBus.json
- docker-dev-cluster/config/ProviderMonitoringNetworkForeignBus.json
> [Fix] Bad RAS line in config files.

- components.pipeline.groovy
- units.pipeline.groovy
> [Chore] Edited Jenkins pipeline files to point to nightly build nodes

- build.gradle
Compatibility with volt 9.1.1.
> [Chore] Update voltctl file for compatibility with Volt 9.1.1

- dai_network_listener/src/main/java/com/intel/dai/network_listener/NetworkListenerSystemActions.java
- docker-deploy/etc/ProviderMonitoringNetworkForeignBus.json
- monitoring/src/main/java/com/intel/dai/monitoring/DemoEnvironmentalProviderForeignBus.java
- monitoring/src/main/java/com/intel/dai/monitoring/DemoEventProviderForeignBus.java
- monitoring/src/test/groovy/com/intel/dai/monitoring/DemoEnvironmentalProviderForeignBusSpec.groovy
- monitoring/src/test/groovy/com/intel/dai/monitoring/DemoEventProviderForeignBusSpec.groovy
These are the Demo files asked for.
> [Demo] Code specifically for a demo.

- dai_core/src/test/java/com/intel/dai/dsimpl/voltdb/VoltDbClientTest.java
> [Fix] Edit to VoltDbClientTest to make the tests more deterministic

- units.pipeline.groovy
> [Chore] Update UT pipeline for inventory api change

- eventsim/src/main/java/com/intel/dai/eventsim/ApiReqData.java
- eventsim/src/main/java/com/intel/dai/eventsim/Component.java
- eventsim/src/main/java/com/intel/dai/eventsim/ConnectionManager.java
- eventsim/src/main/java/com/intel/dai/eventsim/ConnectionObject.java
- eventsim/src/main/java/com/intel/dai/eventsim/DataLoaderEngine.java
- eventsim/src/main/java/com/intel/dai/eventsim/EventSimApp.java
- eventsim/src/main/java/com/intel/dai/eventsim/SimulatorEngine.java
- eventsim/src/main/java/com/intel/dai/eventsim/SystemGenerator.java
- eventsim/src/test/java/com/intel/dai/eventsim/SimulatorEngineTest.java
- findBugsExclusions.xml
- foreign_bus/src/main/java/com/intel/dai/foreign_bus/CommonFunctions.java
- foreign_bus/src/test/java/com/intel/dai/foreign_bus/CommonFunctionsTest.java
> [FIX] spot bugs

- networking/src/main/java/com/intel/networking/restclient/apache/ApacheRESTClient.java
> [Fix] Thread blocking bug.

- eventsim/src/main/java/com/intel/dai/eventsim/ApiReqData.java
- eventsim/src/main/java/com/intel/dai/eventsim/SystemGenerator.java
- eventsim/src/test/java/com/intel/dai/eventsim/SimulatorEngineTest.java
[FIX] CTRL-6752 Eventsim fails to generate events with > node count
> [FIX] CTRL-6752 Eventsim fails to generate events with > node count

- dai_network_listener/src/main/java/com/intel/dai/network_listener/NetworkListenerCore.java
- inventory_api/src/main/java/com/intel/dai/inventory/api/HWInvDiscovery.java
> [Fix] Last of my coverity fixes.

- config-files/BootParameters.json
- dai_core/src/main/java/com/intel/dai/dsapi/BootState.java
- eventsim/src/main/java/com/intel/dai/eventsim/BootParameters.java
- eventsim/src/main/java/com/intel/dai/eventsim/EventSimApp.java
- eventsim/src/test/groovy/com/intel/dai/eventsim/EventSimAppSpec.groovy
- eventsim/src/test/java/com/intel/dai/eventsim/BootParametersTest.java
- provisioners/src/main/java/com/intel/dai/provisioners/NetworkListenerProviderForeignBus.java
- provisioners/src/test/java/com/intel/dai/provisioners/NetworkListenerProviderForeignBusTest.java
> [FEAT] boot image

- config-files/EventSim.json
- eventsim/src/main/java/com/intel/dai/eventsim/ApiReqData.java
- eventsim/src/main/java/com/intel/dai/eventsim/ConnectionManager.java
- eventsim/src/main/java/com/intel/dai/eventsim/NetworkObject.java
- eventsim/src/main/java/com/intel/dai/eventsim/SystemGenerator.java
- eventsim/src/test/groovy/com/intel/dai/eventsim/ConnectionManagerSpec.groovy
- eventsim/src/test/groovy/com/intel/dai/eventsim/NetworkObjectSpec.groovy
> [FIX] eventsim coverity issues

- eventsim/src/main/java/com/intel/dai/eventsim/ApiReqData.java
- eventsim/src/main/java/com/intel/dai/eventsim/BootParameters.java
- eventsim/src/main/java/com/intel/dai/eventsim/ForeignEventBoot.java
- provisioners/src/main/java/com/intel/dai/provisioners/NetworkListenerProviderForeignBus.java
- provisioners/src/test/java/com/intel/dai/provisioners/NetworkListenerProviderForeignBusTest.java
> [FIX] boot events format for locations

- dai_network_listener/src/main/java/com/intel/dai/network_listener/NetworkListenerSystemActions.java
- inventory_api/src/main/java/com/intel/dai/inventory/api/HWInvDiscovery.java
- inventory_api/src/test/groovy/com/intel/dai/inventory/api/HWInvDiscoverySpec.groovy
> HW inv initialize rest client.

- config-files/ProviderInventoryNetworkForeignBus.json
> HW inv adapter config added.

- build.gradle
- gradlew.bat
> [Fix] Made the installer generic and not git version specific.

- dai_core/src/main/java/com/intel/dai/Adapter.java
- dai_core/src/main/java/com/intel/dai/AdapterNearlineTierVolt.java
- dai_core/src/main/java/com/intel/dai/AdapterOnlineTier.java
- dai_core/src/main/java/com/intel/dai/NearlineTableUpdater.java
- dai_core/src/main/java/com/intel/dai/dsimpl/jdbc/DataLoaderApiJdbc.java
- dai_core/src/test/java/com/intel/dai/AdapterOnlineTierTest.java
- data/db/DAI-Tier2-Schema-Psql.sql
- data/db/DAI-Volt-Tables.sql
- procedures/src/main/java/com/intel/dai/procedures/DataMoverGetListOfRecsToMove.java
Signed-off-by: Naian Sai <naian.sai@intel.com>
> [FEAT] Implementing data mover and restore from Tier2 for HW Inventory

- cli/cli/src/tests/test_view.py
- cli/cli/src/tests/test_view_events_summary.py
- cli/cli/src/view.py
- cli_eventsim/cli2/src/tests/test_events.py
- cli_eventsim/cli2/src/tests/test_wlm.py
- data/db/DAI-Tier2-Schema-Psql.sql
- ui/src/main/java/com/intel/dai/ui/CannedAPI.java
- ui/src/test/java/com/intel/dai/ui/AdapterUIRestTest.java
- ui/src/test/java/com/intel/dai/ui/CannedApiTest.java
> [FEAT] HW INV CLI

- build.gradle
- dai_core/src/main/java/com/intel/dai/dsapi/RasEventLog.java
- dai_core/src/main/java/com/intel/dai/dsimpl/voltdb/VoltDbRasEventLog.java
- dai_core/src/test/groovy/com/intel/dai/dsimpl/voltdb/VoltDbRasEventLogSpec.groovy
- dai_core/src/test/java/com/intel/dai/dsimpl/voltdb/VoltDbRasEventLogTest.java
- dai_network_listener/src/main/java/com/intel/dai/network_listener/NetworkListenerSystemActions.java
- dai_network_listener/src/test/groovy/com/intel/dai/network_listener/NetworkListenerSystemActionsSpec.groovy
- dai_network_listener/src/test/java/com/intel/dai/network_listener/NetworkListenerSystemActionsTest.java
- eventsim/src/test/java/com/intel/dai/eventsim/SimulatorEngineTest.java
- findBugsExclusions.xml
- procedures/src/main/java/com/intel/dai/procedures/HwInventoryHistoryInsert.java
- ras/src/main/java/com/intel/dai/ras/AdapterRasForeignBus.java
- ras/src/test/groovy/com/intel/dai/ras/AdapterRasForeignBusSpec.groovy
[Fix] gradle bug fix.
[Fix] RPM voltctl fix.
> [Fix] Performance tuning for release.

- cli/ucs_completion.sh
> [FIX] adding hw inventory commands to autocomplete

- build.gradle
> [Fix] RPM and JAR version fix.

- data/db/DAI-Tier2-Schema-Psql.sql
> [FIX] Maping a xname to subtree nodes data to display inventory info

- inventory_api/src/integration/resources/scripts/hw-inv.sql
> HW inventory component test update

- provisioners/src/main/java/com/intel/dai/provisioners/NetworkListenerProviderForeignBus.java
> [FIX] fetch boot image id for xnames instead of locations

- build.gradle
- docker-deploy/etc/LocationTranslationMap.json
- eventsim/src/main/java/com/intel/dai/eventsim/Component.java
- eventsim/src/main/java/com/intel/dai/eventsim/DataLoaderEngine.java
- eventsim/src/main/java/com/intel/dai/eventsim/EventSimApp.java
- eventsim/src/main/java/com/intel/dai/eventsim/SimulatorEngine.java
- eventsim/src/main/java/com/intel/dai/eventsim/SystemGenerator.java
- eventsim/src/test/groovy/com/intel/dai/eventsim/EventSimAppSpec.groovy
- eventsim/src/test/java/com/intel/dai/eventsim/EventSimAppTest.java
- foreign_bus/src/main/java/com/intel/dai/foreign_bus/CommonFunctions.java
- foreign_bus/src/main/java/com/intel/dai/foreign_bus/ConversionException.java
- foreign_bus/src/test/groovy/com/intel/dai/foreign_bug/ConversionExceptionSpec.groovy
- foreign_bus/src/test/java/com/intel/dai/foreign_bus/CommonFunctionsTest.java
- inventory/src/main/java/com/intel/dai/inventory/NetworkListenerProviderForeignBus.java
- inventory/src/test/groovy/com/intel/dai/inventory/NetworkListenerProviderForeignBusSpec.groovy
- inventory_api/src/main/java/com/intel/dai/inventory/api/ForeignHWInventory.java
- inventory_api/src/main/java/com/intel/dai/inventory/api/ForeignHwInventoryRequester.java
- inventory_api/src/main/java/com/intel/dai/inventory/api/HWInvDiscovery.java
- inventory_api/src/main/java/com/intel/dai/inventory/api/HWInvDiscoveryCLI.java
- inventory_api/src/main/java/com/intel/dai/inventory/api/HWInvTranslator.java
- inventory_api/src/main/java/com/intel/dai/inventory/api/RestRequester.java
- inventory_api/src/test/groovy/com/intel/dai/inventory/api/ForeignHWInventorySpec.groovy
- inventory_api/src/test/groovy/com/intel/dai/inventory/api/HWInvTranslatorSpec.groovy
- inventory_api/src/test/resources/data/foreignHwByLoc/translated/flatNode.json
- monitoring/src/main/java/com/intel/dai/monitoring/EnvironmentalProviderForeignBus.java
- monitoring/src/main/java/com/intel/dai/monitoring/RasEventProviderForeignBus.java
- networking/src/main/java/com/intel/networking/sink/restsse/NetworkDataSinkSSE.java
- networking/src/test/java/com/intel/networking/sink/restsse/NetworkDataSinkSSETest.java
- provisioners/src/main/java/com/intel/dai/provisioners/NetworkListenerProviderForeignBus.java
> [Fix] Fixed circular dependency between components.

- docker-deploy/etc/LocationTranslationMap.json
- docker-deploy/etc/ProviderInventoryNetworkForeignBus.json
- docker-deploy/etc/ProviderProvisionerNetworkForeignBus.json
- monitoring/src/main/java/com/intel/dai/monitoring/DemoEnvironmentalProviderForeignBus.java
- monitoring/src/test/groovy/com/intel/dai/monitoring/DemoEnvironmentalProviderForeignBusSpec.groovy
- networking/src/main/java/com/intel/networking/restserver/java11/SSEConnectionManager.java
> [Fix] some system configuration and fixed a data stream parsing error.

- docker-deploy/etc/ProviderInventoryNetworkForeignBus.json
- docker-deploy/etc/ProviderProvisionerNetworkForeignBus.json
- networking/src/main/java/com/intel/networking/restserver/java11/Java11RESTServer.java
> [Fix] Thread the RESTServer implementation.

- cli_eventsim/cli2/src/events.py
- cli_eventsim/cli2/src/tests/test_events.py
- eventsim/src/main/java/com/intel/dai/eventsim/EventSim.java
- eventsim/src/main/java/com/intel/dai/eventsim/EventSimApp.java
- eventsim/src/main/java/com/intel/dai/eventsim/SimulatorEngine.java
- eventsim/src/main/java/com/intel/dai/eventsim/SystemGenerator.java
- eventsim/src/test/groovy/com/intel/dai/eventsim/NetworkObjectSpec.groovy
- eventsim/src/test/java/com/intel/dai/eventsim/BootParametersTest.java
- eventsim/src/test/java/com/intel/dai/eventsim/EventSimAppTest.java
- eventsim/src/test/java/com/intel/dai/eventsim/SimulatorEngineTest.java
> [FEAT] Generate boot off on ready events

- data/db/DAI-Tier2-Schema-Psql.sql
- demo/demo-v2/js/ajax_calls_functions.js
- demo/demo-v2/js/classes_required.js
- demo/demo-v2/js/functions_javascript.js
- demo/demo-v2/js/functions_javascript_volt.js
> [FIX] Inventory GUI changes

- data/db/DAI-Tier2-Schema-Psql.sql
- demo/demo-v2/js/ajax_calls_functions.js
- demo/demo-v2/js/functions_javascript.js
> [FIX] replacement history gui changes

- docker-build/docker-build.sh
[FIX] Fixed error in docker build script
> [FIX] Fix error in docker build script

- README.md
> [Chore] Edits to README for spelling, grammar and correctness

- dai_core/src/main/java/com/intel/dai/NearlineTableUpdater.java
- populate_schema/src/main/java/com/intel/dai/populate/OnlineTierDataLoader.java
- populate_schema/src/test/java/com/intel/dai/populate/OnlineTierDataLoaderTest.java
> [Feat-Remove] Remove saving/loading data from tier 2 on start.

- eventsim/src/main/java/com/intel/dai/eventsim/ConnectionManager.java
> [FIX] Send each event to all connections instead vice-versa

- README.md
- build.gradle
- docker-deploy/dai.yml
- docker-deploy/etc/EventSim.json
- docker-deploy/etc/HWInvDiscoveryConfig.json
- docker-deploy/etc/MachineConfig.json
- docker-deploy/etc/NearlineConfig.json
- docker-deploy/etc/ProviderInventoryNetworkForeignBus.json
- docker-deploy/etc/ProviderMonitoringNetworkForeignBus.json
- docker-deploy/tier1/init.d/docker-entrypoint.sh
- docker-deploy/voltdb.yml
> [Fix] Documentation, and configuration changes.

- README.md
> [FIX] Corrected script name in README

- dai_network_listener/src/main/java/com/intel/dai/network_listener/NetworkListenerCore.java
- monitoring/src/main/java/com/intel/dai/monitoring/EnvironmentalProviderForeignBus.java
- monitoring/src/main/java/com/intel/dai/monitoring/RasEventProviderForeignBus.java
- monitoring/src/test/java/com/intel/dai/monitoring/EnvironmentalProviderForeignBusTest.java
- monitoring/src/test/java/com/intel/dai/monitoring/RasEventProviderForeignBusTest.java
> [Fix] Wrong negative behavior in monitoring is fixed.

- docker-deploy/tier1/init.d/docker-entrypoint.sh
> [Fix] Voltdb startup log added.

- config-files/EventSim.json
- config-files/HWInvDiscoveryConfig.json
- config-files/ProviderInventoryNetworkForeignBus.json
- dai_network_listener/src/main/java/com/intel/dai/network_listener/BenchmarkingSystemActions.java
- dai_network_listener/src/main/java/com/intel/dai/network_listener/NetworkListenerSystemActions.java
- dai_network_listener/src/main/java/com/intel/dai/network_listener/SystemActions.java
- dai_network_listener/src/test/groovy/com/intel/dai/network_listener/BenchmarkingSystemActionsSpec.groovy
- dai_network_listener/src/test/groovy/com/intel/dai/network_listener/NetworkListenerSystemActionsSpec.groovy
- inventory/src/main/java/com/intel/dai/inventory/AdapterInventoryNetworkBase.java
- inventory/src/main/java/com/intel/dai/inventory/NetworkListenerProviderForeignBus.java
- inventory/src/main/java/com/intel/dai/inventory/ProviderInventoryNetworkForeignBus.java
- inventory/src/test/groovy/com/intel/dai/inventory/AdapterInventoryNetworkBaseSpec.groovy
- inventory/src/test/groovy/com/intel/dai/inventory/NetworkListenerProviderForeignBusSpec.groovy
- inventory_api/src/main/java/com/intel/dai/inventory/api/HWInvDiscovery.java
- inventory_api/src/main/java/com/intel/dai/inventory/api/HWInvDiscoveryCLI.java
- inventory_api/src/test/groovy/com/intel/dai/inventory/api/HWInvDiscoverySpec.groovy
- inventory_api/src/test/groovy/com/intel/dai/inventory/api/HWInvTranslatorSpec.groovy
- inventory_api/src/test/resources/data/foreignHwInventory/missingFormat.json
- inventory_api/src/test/resources/data/foreignHwInventory/nodeNoMemoryNoCpu.json
- provisioners/src/main/java/com/intel/dai/provisioners/NetworkListenerProviderForeignBus.java
> [FIX] delete inderrt operation into replacement history

- data/db/DAI-Tier2-Schema-Psql.sql
- data/db/DAI-Volt-Tables.sql
- eventsim/src/main/java/com/intel/dai/eventsim/WlmApi.java
- resource_managers/src/main/java/com/intel/dai/resource_managers/cobalt/AdapterWlmCobalt.java
- resource_managers/src/test/groovy/com/intel/dai/resource_managers/cobalt/AdapterWlmCobalt.groovy
Fixing simulation issues and removing unnecessary code.
> [FIX] Fixing issues found during simulation.

- eventsim/src/main/java/com/intel/dai/eventsim/ConnectionManager.java
- eventsim/src/main/java/com/intel/dai/eventsim/ConnectionObject.java
- eventsim/src/main/java/com/intel/dai/eventsim/DataLoaderEngine.java
- eventsim/src/main/java/com/intel/dai/eventsim/EventSimApp.java
- eventsim/src/main/java/com/intel/dai/eventsim/ForeignEventRAS.java
> [FIX] eventsim code comments

- dai_core/src/test/groovy/com/intel/dai/dsimpl/voltdb/DsimplVoltdbSpec.groovy
> [FIX] Mocking voltdb instance before fetching it

- inventory/src/main/java/com/intel/dai/inventory/ForeignSubscriptionRequest.java
- inventory/src/main/java/com/intel/dai/inventory/ForeignSubscriptionResponseParser.java
- inventory_api/src/main/java/com/intel/dai/inventory/api/ForeignHwInventoryRequester.java
- inventory_api/src/main/java/com/intel/dai/inventory/api/HWInvDiscovery.java
- inventory_api/src/main/java/com/intel/dai/inventory/api/HWInvNotificationTranslator.java
- inventory_api/src/main/java/com/intel/dai/inventory/api/HWInvTranslatorCLI.java
> [FIX] inventory code comments

- dai_network_listener/src/main/java/com/intel/dai/network_listener/BenchmarkingSystemActions.java
- dai_network_listener/src/main/java/com/intel/dai/network_listener/CommonDataFormat.java
- dai_network_listener/src/main/java/com/intel/dai/network_listener/DataType.java
- dai_network_listener/src/main/java/com/intel/dai/network_listener/Initializer.java
- dai_network_listener/src/main/java/com/intel/dai/network_listener/NetworkListenerConfig.java
- dai_network_listener/src/main/java/com/intel/dai/network_listener/NetworkListenerCore.java
- dai_network_listener/src/main/java/com/intel/dai/network_listener/NetworkListenerSystemActions.java
- dai_network_listener/src/main/java/com/intel/dai/network_listener/SystemActions.java
- monitoring/src/main/java/com/intel/dai/monitoring/AdapterMonitoringNetworkBase.java
- monitoring/src/main/java/com/intel/dai/monitoring/EnvironmentalProviderForeignBus.java
- monitoring/src/main/java/com/intel/dai/monitoring/ProviderMonitoringNetworkForeignBus.java
- monitoring/src/main/java/com/intel/dai/monitoring/RasEventProviderForeignBus.java
- monitoring/src/main/java/com/intel/dai/monitoring/SSEStreamRequestBuilder.java
- monitoring/src/main/java/com/intel/dai/monitoring/SensorMetaDataForeignBus.java
- networking/src/main/java/com/intel/networking/restclient/EventSource.java
- networking/src/main/java/com/intel/networking/restclient/PermissiveX509TrustManager.java
- networking/src/main/java/com/intel/networking/restclient/RESTClientException.java
- networking/src/main/java/com/intel/networking/restclient/RequestInfo.java
- networking/src/main/java/com/intel/networking/restclient/java11/SSELineSubscriber.java
- networking/src/main/java/com/intel/networking/restserver/DefaultResponseTranslator.java
- networking/src/main/java/com/intel/networking/restserver/java11/HttpExchangeRequest.java
- networking/src/main/java/com/intel/networking/restserver/java11/HttpExchangeResponse.java
- networking/src/main/java/com/intel/networking/restserver/java11/Java11RESTServer.java
- networking/src/main/java/com/intel/networking/restserver/java11/SSEConnectionManager.java
- networking/src/main/java/com/intel/networking/sink/http_callback/NetworkDataSinkHttpCallback.java
- networking/src/main/java/com/intel/networking/sink/http_callback/SubjectMessagePair.java
- networking/src/main/java/com/intel/networking/sink/http_callback/SubscriptionRequestBuilder.java
- networking/src/main/java/com/intel/networking/sink/http_callback/SubscriptionResponseParser.java
- networking/src/main/java/com/intel/networking/source/rabbitmq/NetworkDataSourceRabbitMQ.java
> [Doc] Added comments to code I have worked on recently.

- docs/VoltDBNotes.md
> [Doc] Information on the VoltDB issue found.

- README.md
- docs/EnvironmentalProviderForeignBusConfiguration.md
- docs/ProviderInventoryNetworkForeignBusConfiguration.md
- docs/UnderstandingDaiNetworkListenerConfigurations.md
> [DOC] Readme typo fix

- monitoring/src/main/java/com/intel/dai/monitoring/DemoEnvironmentalProviderForeignBus.java
> [Fix] New Coverity issue.

- docs/SimulationCLISetupAndUsage.md
- docs/SimulationSetupAndUsage.md
[DOC] EventSim CLI setup and usage doc
> [DOC] EventSim and CLI Setup and usage

- data/etc-logstash/conf.d/cobalt-bgsched.conf
- data/etc-logstash/conf.d/cobalt-cqm.conf
- docs/SimulationCLISetupAndUsage.md
> [Fix] Change default cobalt logstash configuration

- build.gradle
> [Fix] Developer docker test tarball name and contents.

- dai_core/src/main/java/com/intel/dai/Adapter.java
> [Fix] Solved the Cobalt WLM adapter extra instances.

- dai_core/src/main/java/com/intel/dai/Adapter.java
> [Fix] This is a broader fix to the RAS/WLM integration bug.

- build.gradle
- inventory_api/src/test/groovy/com/intel/dai/inventory/api/CommonCliUtilSpec.groovy
- inventory_api/src/test/groovy/com/intel/dai/inventory/api/HWInvDiscoverySpec.groovy
- inventory_api/src/test/groovy/com/intel/dai/inventory/api/HWInvTranslatorSpec.groovy
> Increased HW Inv API code coverage.

- build.gradle
> [Feat] Enable CC gating in TravisCI.

- docs/DatabaseConnectionConfiguration.md
- docs/UCSCommandLineUserGuide.md
> [Chore] Added documentation for Database Connection and updated CLI guide

- docs/UCSCommandLineUserGuide.md
> [Chore] Add examples to UCS command line user guide

- config-files/HWInvDiscoveryConfig.json
- dai_core/src/main/java/com/intel/dai/dsimpl/voltdb/VoltHWInvApi.java
- dai_core/src/test/groovy/com/intel/dai/dsimpl/voltdb/VoltHWInvApiSpec.groovy
- docker-deploy/etc/HWInvDiscoveryConfig.json
- docker-deploy/etc/ProviderInventoryNetworkForeignBus.json
- docker-deploy/etc/ProviderProvisionerNetworkForeignBus.json
- inventory_api/src/main/java/com/intel/dai/inventory/api/HWDiscoverySession.java
- inventory_api/src/main/java/com/intel/dai/inventory/api/HWInvDiscovery.java
- inventory_api/src/main/java/com/intel/dai/inventory/api/HWInvTranslator.java
- pipelines/units.pipeline.groovy
- units.pipeline.groovy
> Enable HSM State Change Notifications on Inventory and Provisioner Adapters

- build.gradle
- dai_core/src/main/java/com/intel/dai/dsimpl/voltdb/VoltHWInvApi.java
- dai_network_listener/src/main/java/com/intel/dai/network_listener/BenchmarkingSystemActions.java
- dai_network_listener/src/main/java/com/intel/dai/network_listener/NetworkListenerSystemActions.java
- dai_network_listener/src/main/java/com/intel/dai/network_listener/SystemActions.java
- dai_network_listener/src/test/groovy/com/intel/dai/network_listener/NetworkListenerSystemActionsSpec.groovy
- inventory/src/main/java/com/intel/dai/inventory/AdapterInventoryNetworkBase.java
- inventory/src/main/java/com/intel/dai/inventory/ForeignInvApi.java
- inventory/src/main/java/com/intel/dai/inventory/NetworkListenerProviderForeignBus.java
- inventory/src/main/java/com/intel/dai/inventory/ProviderInventoryNetworkForeignBus.java
- inventory/src/test/groovy/com/intel/dai/inventory/AdapterInventoryNetworkBaseSpec.groovy
- inventory/src/test/groovy/com/intel/dai/inventory/ForeignInvApiSpec.groovy
- inventory_api/src/main/java/com/intel/dai/inventory/api/HWInvDiscovery.java
> Removed inv api dependency from dai network listener.

- eventsim/src/main/java/com/intel/dai/eventsim/CallBackNetwork.java
- eventsim/src/main/java/com/intel/dai/eventsim/Component.java
- eventsim/src/main/java/com/intel/dai/eventsim/SystemGenerator.java
- eventsim/src/test/groovy/com/intel/dai/eventsim/CallBackNetworkSpec.groovy
> [FIX] remaning function to correct build issues

- eventsim/src/main/java/com/intel/dai/eventsim/ForeignEvent.java
- eventsim/src/main/java/com/intel/dai/eventsim/NetworkConnectionObject.java
> [FIX] switch notifications from callback to sse

- eventsim/src/main/java/com/intel/dai/eventsim/SimulatorEngine.java
> [FIX] changing console statements to log debug statements

- docker-deploy/etc/ProviderInventoryNetworkForeignBus.json
- docker-deploy/etc/ProviderProvisionerNetworkForeignBus.json
> [Fix] Docker configuration fix.

- cli_eventsim/cli2/src/events.py
- cli_eventsim/cli2/src/tests/test_events.py
> [FIX] Eventsim scenario help description for units.

- docker-deploy/etc/HWInvDiscoveryConfig.json
> [Fix] Removed Authentication check from Inv config

- procedures/src/main/java/com/intel/dai/procedures/HwInventoryHistoryInsert.java
- procedures/src/main/java/com/intel/dai/procedures/HwInventoryHistoryLastUpdateTimestamp.java
> [Fix] Fix issues with mismatching Volt procedures

- procedures/src/main/java/com/intel/dai/procedures/HwInventoryHistoryEventCount.java
> Typo in stored procedure.

- docker-deploy/etc/ProviderMonitoringNetworkForeignBus.json
- monitoring/src/main/java/com/intel/dai/monitoring/EventSimEnvironmentalProviderForeignBus.java
- monitoring/src/main/java/com/intel/dai/monitoring/EventSimRasEventProviderForeignBus.java
- monitoring/src/main/java/com/intel/dai/monitoring/SensorMetaDataForeignBus.java
- monitoring/src/test/java/com/intel/dai/monitoring/EventSimEnvironmentalProviderForeignBusTest.java
- monitoring/src/test/java/com/intel/dai/monitoring/EventSimRasEventProviderForeignBusTest.java
- monitoring/src/test/java/com/intel/dai/monitoring/SensorMetaDataForeignBusTest.java
> [Fix] Added legacy support for eventsim while its in re-design.

- data/db/DAI-Tier2-Schema-Psql.sql
- fabric/src/main/java/com/intel/dai/fabric/FabricAdapter.java
- fabric/src/main/java/com/intel/dai/fabric/FabricPerfTelemetryProvider.java
- fabric/src/main/java/com/intel/dai/fabric/FabricTelemetryProvider.java
- networking/src/main/java/com/intel/networking/sink/restsse/NetworkDataSinkSSE.java
> [Fix] Multiple bug fixes in new fabric adapters.

- docker-deploy/eventsim-config/EventSim.json
> [Fix] Correct Eventsim stream URLs

- cli/cli/src/view.py
- dai_core/src/integration/groovy/com/intel/dai/dsimpl/voltdb/VoltHWInvDbApiITSpec.groovy
- dai_core/src/main/java/com/intel/dai/dsimpl/voltdb/VoltHWInvDbApi.java
- data/db/DAI-Tier2-Schema-Psql.sql
- inventory_api/src/integration/resources/scripts/clean_up_machine.sh
- inventory_api/src/integration/resources/scripts/start-voltdb.sh
- pipelines/units.pipeline.groovy
> jdbc dataflow for unified node inventory.

- docker-deploy/eventsim-config/EventSim.json
- docker-deploy/eventsim-config/ProviderMonitoringNetworkForeignBus.json
> [Fix] Correct Eventsim APIs

- dai_network_listener/src/main/java/com/intel/dai/network_listener/NetworkListenerCore.java
- fabric/src/main/java/com/intel/dai/fabric/FabricAdapter.java
- networking/src/main/java/com/intel/networking/restserver/java11/SSEConnectionManager.java
> [Fix] SSE caused performance regression fix attempt.

- config-files/EventSim.json
- config-files/FabricCritTelemetryProvider.json
- config-files/FabricPerfTelemetryProvider.json
- config-files/FabricTelemetryProvider.json
- config-files/HWInvDiscoveryConfig.json
- config-files/ProviderInventoryNetworkForeignBus.json
- config-files/ProviderMonitoringNetworkForeignBus.json
- config-files/ProviderProvisionerNetworkForeignBus.json
- docker-deploy/eventsim-config/EventSim.json
- docker-deploy/eventsim-config/FabricCritTelemetryProvider.json
- docker-deploy/eventsim-config/FabricPerfTelemetryProvider.json
- docker-deploy/eventsim-config/FabricTelemetryProvider.json
- docker-deploy/eventsim-config/ProviderInventoryNetworkForeignBus.json
- docker-deploy/eventsim-config/ProviderMonitoringNetworkForeignBus.json
- docker-deploy/eventsim-config/ProviderProvisionerNetworkForeignBus.json
> [FIX] correction to configuration details

- cli_eventsim/eventsim_cli_config.json
- dai_network_listener/src/main/java/com/intel/dai/network_listener/NetworkListenerConfig.java
- dai_network_listener/src/test/java/com/intel/dai/network_listener/NetworkListenerConfigTest.java
- docker-deploy/eventsim-config/EventsTemplate.json
- provisioners/src/main/java/com/intel/dai/provisioners/NetworkListenerProviderForeignBus.java
- provisioners/src/test/java/com/intel/dai/provisioners/NetworkListenerProviderForeignBusTest.java
> [FIX] provisioner adapter url changes

- dai_core/src/main/java/com/intel/dai/NearlineTableUpdater.java
- dai_core/src/main/java/com/intel/dai/dsapi/HWInvDbApi.java
- dai_core/src/main/java/com/intel/dai/dsimpl/jdbc/DataLoaderApiJdbc.java
- data/db/DAI-Tier2-Schema-Psql.sql
- inventory_api/src/integration/resources/scripts/clean_up_machine.sh
- pipelines/units.components.pipeline.groovy
> Data mover changes for unified node inventory table.

- config-files/EventSim.json
- config-files/EventsTemplate.json
- config-files/ProviderInventoryNetworkForeignBus.json
- config-files/ProviderMonitoringNetworkForeignBus.json
- config-files/ProviderProvisionerNetworkForeignBus.json
- dai_network_listener/src/main/java/com/intel/dai/network_listener/NetworkListenerConfig.java
- docker-deploy/eventsim-config/EventSim.json
- docker-deploy/eventsim-config/EventsTemplate.json
- docker-deploy/eventsim-config/ProviderInventoryNetworkForeignBus.json
- docker-deploy/eventsim-config/ProviderMonitoringNetworkForeignBus.json
- docker-deploy/eventsim-config/ProviderProvisionerNetworkForeignBus.json
- eventsim/src/main/java/com/intel/dai/eventsim/SSENetwork.java
- networking/src/main/java/com/intel/networking/restserver/java11/Java11RESTServer.java
- networking/src/main/java/com/intel/networking/restserver/java11/SSEConnectionManager.java
> [FIX] send network data to subscribed url only

- docker-deploy/dai.yml
- docker-deploy/eventsim-config/EventSim.json
- docker-deploy/eventsim-config/MachineConfig.json
- docker-deploy/eventsim-config/NearlineConfig.json
- docker-deploy/eventsim.yml
- docker-deploy/voltdb.yml
> [Fix] Hostname fixes for eventsim and docker-compose.

- docker-deploy/dai.yml
- docker-deploy/eventsim-config/EventSim.json
- docker-deploy/eventsim-config/MachineConfig.json
- docker-deploy/eventsim-config/NearlineConfig.json
- docker-deploy/eventsim.yml
- docker-deploy/voltdb.yml
Reverts unifiedcontrolsystem/dai-ds#172
> Revert "[Fix] Hostname fixes for eventsim and docker-compose."

- docker-deploy/dai.yml
- docker-deploy/eventsim-config/EventSim.json
- docker-deploy/eventsim-config/MachineConfig.json
- docker-deploy/eventsim-config/NearlineConfig.json
- docker-deploy/eventsim.yml
- docker-deploy/voltdb.yml
Reverts unifiedcontrolsystem/dai-ds#173
> Revert "Revert "[Fix] Hostname fixes for eventsim and docker-compose.""

- cli_eventsim/eventsim_cli_config.json
- docker-deploy/eventsim-config/ProviderMonitoringNetworkForeignBus.json
> [FIX] correcting providers publish data

- docker-deploy/eventsim-config/NearlineConfig.json
> [FIX] Correct Nearline config hostname

- docker-deploy/eventsim-config/EventSim.json
> [FIX] adding the fabric adapter url details

- docker-deploy/eventsim-config/ProviderMonitoringNetworkForeignBus.json
- fabric/src/main/java/com/intel/dai/fabric/FabricAdapter.java
> [FIX] fixing environmental events to publish

- eventsim/src/main/java/com/intel/dai/eventsim/SSENetwork.java
- monitoring/src/main/java/com/intel/dai/monitoring/EventSimRasEventProviderForeignBus.java
- monitoring/src/test/java/com/intel/dai/monitoring/EventSimRasEventProviderForeignBusTest.java
- networking/src/main/java/com/intel/networking/restclient/apache/ApacheRESTClient.java
> [Fix] Improve eventsim performance.

- dai_core/src/main/java/com/intel/dai/AdapterDaiMgr.java
- docker-deploy/dai.yml
- docker-deploy/hw1-config/LocationTranslationMap.json
- docker-deploy/hw1-config/MachineConfig.json
- docker-deploy/hw1-config/SystemManifest.json
> [Fix] Configuration fixes for hw1.

- build.gradle
> [Fix] Fixed show adapters for containers.

- docker-deploy/hw1-config/HWInvDiscoveryConfig.json
- inventory/src/main/java/com/intel/dai/inventory/api/HWInvDiscovery.java
> Changed rest client to Apache.

- docker-deploy/hw1-config/HWInvDiscoveryConfig.json
- docker-deploy/hw1-config/ProviderInventoryNetworkForeignBus.json
- docker-deploy/hw1-config/ProviderMonitoringNetworkForeignBus.json
- inventory/src/main/java/com/intel/dai/inventory/NetworkListenerProviderForeignBus.java
- networking/src/main/java/com/intel/networking/restclient/RESTClient.java
- networking/src/main/java/com/intel/networking/restclient/apache/ApacheRESTClient.java
- networking/src/test/groovy/com/intel/networking/restclient/apache/ApacheRESTClientSpec.groovy
> [Fix] Fixing missing OAuth2 token in REST calls.

- docs/SimulationSetupAndUsage.md
> [FIX] ipdlt documentation issue

- build.gradle
> [Update] Update the keycloak lib from 8.0.1 to 10.0.2.

- config-files/ProviderInventoryNetworkForeignBus.json
- config-files/ProviderProvisionerNetworkForeignBus.json
- docker-deploy/eventsim-config/ProviderInventoryNetworkForeignBus.json
- docker-deploy/eventsim-config/ProviderProvisionerNetworkForeignBus.json
- docker-deploy/hw1-config/ProviderInventoryNetworkForeignBus.json
- docker-deploy/hw1-config/ProviderProvisionerNetworkForeignBus.json
- networking/src/main/java/com/intel/networking/sink/sse/EventSourceClient.java
- networking/src/main/java/com/intel/networking/sink/sse/NetworkDataSinkEventSource.java
- networking/src/test/groovy/com/intel/networking/sink/sse/EventSourceClientSpec.groovy
> [Fix] Fix HMS stream over buffering problem.

- eventsim/src/main/java/com/intel/dai/eventsim/ApiReqData.java
- eventsim/src/main/java/com/intel/dai/eventsim/BootParameters.java
- eventsim/src/main/java/com/intel/dai/eventsim/CallBackNetwork.java
- eventsim/src/main/java/com/intel/dai/eventsim/ConnectionManager.java
- eventsim/src/main/java/com/intel/dai/eventsim/DataValidation.java
- eventsim/src/main/java/com/intel/dai/eventsim/HardwareInventory.java
- eventsim/src/main/java/com/intel/dai/eventsim/LoadFileLocation.java
- eventsim/src/main/java/com/intel/dai/eventsim/NetworkConnectionObject.java
- eventsim/src/main/java/com/intel/dai/eventsim/NetworkObject.java
> [Fix] Remove all unused @NotNull references in EventSim.

- dai_network_listener/src/main/java/com/intel/dai/network_listener/CommonDataFormat.java
- fabric/src/main/java/com/intel/dai/fabric/Accumulator.java
- fabric/src/main/java/com/intel/dai/fabric/FabricTelemetryItem.java
- fabric/src/test/groovy/com/intel/dai/fabric/FabricTelemetryItemSpec.groovy
- monitoring/src/main/java/com/intel/dai/monitoring/EnvironmentalProviderForeignBus.java
- monitoring/src/main/java/com/intel/dai/monitoring/EventSimEnvironmentalProviderForeignBus.java
- monitoring/src/test/groovy/com/intel/dai/monitoring/EnvironmentalProviderForeignBusSpec.groovy
> [Fix] Fix health summary data generation.

- build.gradle
- dai_core/src/main/java/com/intel/dai/AdapterDaiMgr.java
- dai_core/src/main/java/com/intel/dai/dsimpl/voltdb/VoltDbRasEventLog.java
- dai_network_listener/src/main/java/com/intel/dai/network_listener/NetworkListenerConfig.java
- dai_network_listener/src/main/java/com/intel/dai/network_listener/NetworkListenerSystemActions.java
- monitoring/src/main/java/com/intel/dai/monitoring/SensorMetaDataForeignBus.java
- networking/src/main/java/com/intel/networking/restclient/apache/ApacheRESTClient.java
- networking/src/main/java/com/intel/networking/restserver/RESTServer.java
- networking/src/main/java/com/intel/networking/restserver/java11/SSEConnectionManager.java
- perflogging/src/main/java/com/intel/perflogging/BenchmarkHelper.java
- perflogging/src/main/java/com/intel/perflogging/PerfLogger.java
- populate_schema/src/main/java/com/intel/dai/populate/DefaultOnlineTierDataLoader.java
- provisioners/src/main/java/com/intel/dai/provisioners/NetworkListenerProviderForeignBus.java
> [Fix] Bugs related to Java 8 source compatibility.

- docker-deploy/hw2-config/ProviderProvisionerNetworkForeignBus.json
- docker-deploy/hw3-config/ProviderProvisionerNetworkForeignBus.json
> [FIX] provisioner configuration changes for hw2 and hw3

- cli_eventsim/cli2/src/events.py
> [FIX] Eventsim cli timezone type

- eventsim/src/main/java/com/intel/dai/eventsim/WlmApi.java
- perflogging/src/main/java/com/intel/perflogging/BenchmarkHelper.java
> [Fix] More Java 8 compatibility fixes wrt FileWriter.

- build.gradle
- eventsim/src/main/java/com/intel/dai/eventsim/EventSimApp.java
- eventsim/src/main/java/com/intel/dai/eventsim/java11/HttpExchangeRequest.java
- eventsim/src/main/java/com/intel/dai/eventsim/java11/HttpExchangeResponse.java
- eventsim/src/main/java/com/intel/dai/eventsim/java11/Java11RESTServer.java
- eventsim/src/main/java/com/intel/dai/eventsim/java11/SSEConnectionManager.java
- eventsim/src/test/groovy/com/intel/dai/eventsim/NetworkObjectSpec.groovy
- eventsim/src/test/groovy/com/intel/dai/eventsim/SSENetworkSpec.groovy
- eventsim/src/test/java/com/intel/dai/eventsim/java11/HttpExchangeRequestTest.java
- eventsim/src/test/java/com/intel/dai/eventsim/java11/HttpExchangeResponseTest.java
- eventsim/src/test/java/com/intel/dai/eventsim/java11/Java11RESTServerTest.java
- eventsim/src/test/java/com/intel/dai/eventsim/java11/SSEConnectionManagerTest.java
- networking/src/main/java/com/intel/networking/restserver/RESTServerFactory.java
> [Refactor] Move java 11 specific REST server to EventSim (its only client)

- components.pipeline.groovy
- docker-deploy/dai/entryPoint.sh
- pipelines/sandbox.units.pipeline.groovy
> Enabled jacoco coverage for functional dai-mgr tests.

- pipelines/experimental.watcher.pipeline.groovy
> Added experimental watcher pipeline.

- pipelines/experimental.units.pipeline.groovy
- pipelines/sandbox.units.pipeline.groovy
- units.pipeline.groovy
> Component tests can no longer run concurrently as unit tests.

- .gitignore
- data/db/DAI-Tier2-Schema-Psql.sql
- pipelines/experimental.units.pipeline.groovy
- pipelines/experimental.watcher.pipeline.groovy
- pipelines/sandbox.units.pipeline.groovy
> Added node location to the output of fru migration history.

- .gitignore
- build.gradle
- data/db/DAI-Tier2-Schema-Psql.sql
- pipelines/experimental.units.pipeline.groovy
- pipelines/sandbox.units.pipeline.groovy
> Cleanup of Postgres inv code.

- cli/cli/src/tests/test_view.py
- cli/cli/src/view.py
- pipelines/experimental.components.pipeline.groovy
- pipelines/experimental.units.pipeline.groovy
- pipelines/experimental.watcher.pipeline.groovy
- pipelines/sandbox.units.pipeline.groovy
> Readability for hw info.

- cli/cli/src/tests/test_view.py
> Fixed a test.

- cli/cli/src/view.py
> Extended ucs view to include component locations.

- eventsim/src/main/java/com/intel/dai/eventsim/ForeignSimulatorEngine.java
> [FIX] setting timestamp path key

- cli/cli/src/view.py
> Refactored for readability; no logic changed.

- cli/cli/src/view.py
> Handles negative cases for cli component view.

- components.pipeline.groovy
- pipelines/experimental.components.pipeline.groovy
- pipelines/experimental.units.pipeline.groovy
- pipelines/sandbox.units.pipeline.groovy
> Fixed build Name issues in pipelines.

- build.gradle
Required to provide compatibility with volt clusters
> [Chore] Change voltdb stop to voltadmin shutdown

- pipelines/experimental.units.pipeline.groovy
- pipelines/sandbox.units.pipeline.groovy
> Added missing agent parameter when launching functional tests.

- docker-deploy/eventsim-config/voltdb.yml
> [Fix] Automation failures due to voltdb failure.

- cli_eventsim/cli2/src/events.py
- cli_eventsim/cli2/src/tests/test_events.py
- eventsim/src/main/java/com/intel/dai/eventsim/EventSimApp.java
- eventsim/src/main/java/com/intel/dai/eventsim/ForeignSimulatorEngine.java
- eventsim/src/test/groovy/com/intel/dai/eventsim/EventSimAppSpec.groovy
- eventsim/src/test/groovy/com/intel/dai/eventsim/ForeignSimulatorEngineSpec.groovy
- eventsim/src/test/java/com/intel/dai/eventsim/EventSimAppTest.java
> [FEAT] list available locations in system

- build.gradle
> Added more version variables to build.gradle.

- cli/cli/src/tests/test_view.py
- cli/cli/src/view.py
- cli/ucs_completion.sh
- data/db/DAI-Tier2-Schema-Psql.sql
- ui/src/main/java/com/intel/dai/ui/CannedAPI.java
> Extended ucs view to display fru migration history.

- components.pipeline.groovy
- pipelines/experimental.units.pipeline.groovy
- pipelines/sandbox.units.pipeline.groovy
- units.pipeline.groovy
> Reduced emails.

- cli/cli/src/tests/test_view.py
> Added pytests for fru-migration.

- build.gradle
- config-files/MachineConfig.json
- dai_core/src/main/java/com/intel/dai/Adapter.java
- dai_core/src/main/java/com/intel/dai/AdapterDaiMgr.java
- dai_core/src/main/java/com/intel/dai/IAdapter.java
- dai_core/src/main/java/com/intel/dai/dsapi/WorkQueue.java
- dai_core/src/main/java/com/intel/dai/dsimpl/voltdb/VoltDbWorkQueue.java
- dai_core/src/test/groovy/com/intel/dai/AdapterDaiMgrSpec.groovy
- docker-deploy/dai/entryPoint.sh
- docker-deploy/eventsim-config/MachineConfig.json
- docker-deploy/eventsim-config/dai.yml
- docker-deploy/hw1-config/MachineConfig.json
- docker-deploy/hw1-config/dai.yml
- docker-deploy/hw2-config/MachineConfig.json
- docker-deploy/hw2-config/dai.yml
- docker-deploy/hw3-config/MachineConfig.json
- docker-deploy/hw3-config/dai.yml
> [Fix] Adding new AdapterDaiMgr and tests.

- dai_core/src/main/java/com/intel/dai/Adapter.java
- dai_core/src/main/java/com/intel/dai/dsimpl/voltdb/VoltDbAdapterOperations.java
- fabric/src/main/java/com/intel/dai/fabric/FabricAdapter.java
- resource_managers/src/main/java/com/intel/dai/resource_managers/cobalt/AdapterWlmCobalt.java
> [Fix] Make logging software events asynchronous in fabric adapter.

- logging/src/main/java/com/intel/logging/LoggerConsole.java
- logging/src/main/java/com/intel/logging/LoggerLog4j2.java
> [Feat] Added DAI_LOGGING_LEVEL env variable for setting level.

- fabric/src/main/java/com/intel/dai/fabric/FabricAdapter.java
> [Fix] Bogus partition table error, was bad input.

- logging/src/main/java/com/intel/logging/LoggerConsole.java
- logging/src/main/java/com/intel/logging/LoggerLog4j2.java
- logging/src/main/java/com/intel/logging/LoggerUtils.java
> [Fix] Moved stack traces to ERROR level.

- dai_core/src/main/java/com/intel/dai/Adapter.java
- dai_network_listener/src/main/java/com/intel/dai/network_listener/NetworkListenerCore.java
- runtime_utils/src/main/java/com/intel/runtime_utils/PropertyLoader.java
> [Fix] Fixed static analysis bugs.

- docs/SimulationCLISetupAndUsage.md
> [DOCS] list-locations command documentation

- eventsim/src/main/java/com/intel/dai/eventsim/ForeignSimulatorEngine.java
> [FIX] send events after completion of waiting time

- config-files/HWInvDiscoveryConfig.json
- docker-deploy/eventsim-config/HWInvDiscoveryConfig.json
- inventory/src/integration/resources/data/HWInvDiscoveryConfig.json
- inventory/src/integration/resources/scripts/json-server/eventsim.inventory.db.json
- inventory/src/integration/resources/scripts/json-server/routes.json
> Added 'Query' to rest call for inventory.

- pipelines/experimental.units.pipeline.groovy
- pipelines/sandbox.units.pipeline.groovy
- units.pipeline.groovy
> [Fix] Scoop up cleanup_machine.sh required for testing

- build.gradle
> [Fix] CLI Package was imcomplete.

- build.gradle
> [Fix] Missing EnvironmentFile line in service file.

- sandbox_pipelines/sandbox.units.pipeline.groovy
> [Fix] sandbox pipeline bug fixed.

- configurations/eventsim/FabricCritTelemetryProvider.json
- configurations/eventsim/FabricPerfTelemetryProvider.json
- configurations/eventsim/FabricTelemetryProvider.json
> [Fix] Bad config causing failing FT for fabric.

- build.gradle
> [Fix] Fixed obscure docker issue.

- build.gradle
> [Fix] CLI install/uninstall issues.

- build.gradle
- networking/src/main/java/com/intel/networking/sink/NetworkDataSinkFactory.java
- networking/src/main/java/com/intel/networking/sink/kafka/NetworkDataSinkKafka.java
- networking/src/test/groovy/com/intel/networking/sink/kafka/NetworkDataSinkKafkaSpec.groovy
- networking/src/test/java/com/intel/networking/sink/NetworkDataSinkFactoryTest.java
> [FEAT] Network data sink kafka

- networking/src/main/java/com/intel/networking/sink/kafka/NetworkDataSinkKafka.java
- networking/src/main/java/com/intel/networking/source/NetworkDataSourceFactory.java
- networking/src/main/java/com/intel/networking/source/kafka/NetworkDataSourceKafka.java
- networking/src/test/groovy/com/intel/networking/sink/kafka/NetworkDataSinkKafkaSpec.groovy
- networking/src/test/groovy/com/intel/networking/source/kafka/NetworkDataSourceKafkaSpec.groovy
> [FEAT] Network DataSource Kafka

- provisioners/src/main/java/com/intel/dai/provisioners/AdapterProvisionerApi.java
- provisioners/src/main/java/com/intel/dai/provisioners/NetworkListenerProviderForeignBus.java
> [FIX] change nanosecond timestamp to micro second timestamp

- configurations/hw1/ProviderProvisionerNetworkForeignBus.json
- networking/src/main/java/com/intel/networking/sink/kafka/NetworkDataSinkKafka.java
- networking/src/test/groovy/com/intel/networking/sink/kafka/NetworkDataSinkKafkaSpec.groovy
> [FEAT] New provisioner adapter to support HPCM

- .travis.yml
- configurations/eventsim/EventSim.json
- eventsim/src/main/java/com/intel/dai/eventsim/DataLoader.java
- eventsim/src/main/java/com/intel/dai/eventsim/DataValidation.java
- eventsim/src/main/java/com/intel/dai/eventsim/ForeignSimulatorEngine.java
- eventsim/src/main/java/com/intel/dai/eventsim/NetworkConnectionObject.java
- eventsim/src/main/java/com/intel/dai/eventsim/NetworkObject.java
- eventsim/src/main/java/com/intel/dai/eventsim/SSENetwork.java
- eventsim/src/test/groovy/com/intel/dai/eventsim/DataLoaderSpec.groovy
- eventsim/src/test/groovy/com/intel/dai/eventsim/DataValidationSpec.groovy
- eventsim/src/test/groovy/com/intel/dai/eventsim/EventSimAppSpec.groovy
- eventsim/src/test/groovy/com/intel/dai/eventsim/NetworkObjectSpec.groovy
- eventsim/src/test/resources/resources/test-config-files/TestConfig.json
- networking/src/main/java/com/intel/networking/source/NetworkDataSourceEx.java
- networking/src/main/java/com/intel/networking/source/kafka/NetworkDataSourceKafka.java
- networking/src/test/groovy/com/intel/networking/source/kafka/NetworkDataSourceKafkaSpec.groovy
> [FEAT] Eventsim to support publishing data HPCM kafka

- cleanup_machine.sh
> [Fix] Add line to cleanup script to ensure consistent test environment

- provisioners/src/main/java/com/intel/dai/provisioners/AdapterProvisionerApi.java
- provisioners/src/main/java/com/intel/dai/provisioners/NetworkListenerProviderForeignBus.java
> [FIX] correcting input timestamps data

- dai_core/src/main/java/com/intel/dai/dsimpl/voltdb/VoltDbAdapterOperations.java
> [FIX] adding timestamp data to log

- data/db/DAI-Tier2-Schema-Psql.sql
Signed-off-by: Naian Sai <naian.sai@intel.com>
> [FIX] : [Tier 2 Schema] Tier2 schema throws error

- configurations/eventsim/MachineConfig.json
- configurations/hw1/MachineConfig.json
- configurations/hw2/MachineConfig.json
- configurations/hw3/MachineConfig.json
> [Fix] Missing new Ucs Values that were missing from merge.

- README.md
> [Doc] Added info about VoltDB huge pages.

- cleanup_machine.sh
- dai_core/src/main/java/com/intel/dai/Adapter.java
- dai_core/src/main/java/com/intel/dai/AdapterNearlineTierVolt.java
- dai_core/src/main/java/com/intel/dai/AdapterOnlineTier.java
- dai_core/src/main/java/com/intel/dai/NearlineTableUpdater.java
- dai_core/src/test/groovy/com/intel/dai/dsimpl/voltdb/HWInvUtilImplSpec.groovy
- dai_core/src/test/java/com/intel/dai/AdapterOnlineTierTest.java
- data/db/DAI-Tier2-Schema-Psql.sql
- inventory/src/integration/resources/scripts/setup_testbed.sh
- inventory/src/integration/resources/scripts/start-voltdb.sh
- inventory/src/integration/resources/scripts/teardown_testbed.sh
- procedures/src/main/java/com/intel/dai/procedures/DataMoverGetListOfRecsToMove.java
> Raw inventory logic.

- docs/UnderstandingDaiNetworkListenerConfigurations.md
- docs/WLMAdapterForeignBusConfiguration.md
> [DOC] kafka documentation

- eventsim/src/test/groovy/com/intel/dai/eventsim/ForeignSimulatorEngineSpec.groovy
> [Fix] Re-enable some @ignored tests.

- resource_managers/src/main/java/com/intel/dai/resource_managers/pbs/AdapterWlmPBS.java
> [Fix] Add network sink shutdown code to pbs_pro wlm.

- configurations/hw1/AdapterWlmPBS.json
- configurations/hw1/ProviderProvisionerNetworkForeignBus.json
- configurations/hw3/AdapterWlmPBS.json
- dai_network_listener/src/main/java/com/intel/dai/network_listener/CommonDataFormat.java
- monitoring/src/main/java/com/intel/dai/monitoring/EnvironmentalProviderHPCM.java
- monitoring/src/test/groovy/com/intel/dai/monitoring/EnvironmentalProviderHPCMSpec.groovy
- networking/src/main/java/com/intel/networking/sink/kafka/NetworkDataSinkKafka.java
- populate_schema/src/test/java/com/intel/dai/populate/OnlineTierDataLoaderTest.java
- runtime_utils/src/main/java/com/intel/runtime_utils/TimeUtils.java
- runtime_utils/src/test/groovy/com/intel/runtime_utils/TimeUtilsSpec.groovy
> [Fix] Added AVRO support in DAI-DS Kafka data sink implementation.

- networking/src/main/java/com/intel/networking/sink/kafka/NetworkDataSinkKafka.java
> [Fix] Skip 'poison pill' message in kafka bus stream.

- build.gradle
[Fix] Add "upgrade" support for python CLIs.
[Fix] Updated dependency's versions for Java code.
> [Fix] Optimize voltdb setup.

- configurations/eventsim/EventSim.json
- configurations/eventsim/EventsTemplate.json
- eventsim/src/main/java/com/intel/dai/eventsim/EventTypeTemplate.java
- eventsim/src/main/java/com/intel/dai/eventsim/ForeignSimulatorEngine.java
- eventsim/src/main/java/com/intel/dai/eventsim/NetworkConnectionObject.java
- eventsim/src/main/java/com/intel/dai/eventsim/NetworkObject.java
- eventsim/src/main/resources/resources/avro/pbs_job_completed.avsc
- eventsim/src/main/resources/resources/avro/pbs_job_started.avsc
- eventsim/src/main/resources/resources/templates/pbs_job_completed.json
- eventsim/src/main/resources/resources/templates/pbs_job_started.json
- eventsim/src/test/groovy/com/intel/dai/eventsim/NetworkObjectSpec.groovy
- eventsim/src/test/resources/resources/test-config-files/TestTemplateConfig.json
- networking/src/main/java/com/intel/networking/source/kafka/NetworkDataSourceKafka.java
- networking/src/test/groovy/com/intel/networking/source/kafka/NetworkDataSourceKafkaSpec.groovy
> [FEAT] eventsim to support avro format on publishing data

- sandbox_pipelines/sandbox.watcher.pipeline.groovy
> Added a param to control heartbeat generation.

- configurations/eventsim/EventsTemplate.json
- eventsim/src/main/java/com/intel/dai/eventsim/DataLoader.java
- eventsim/src/main/java/com/intel/dai/eventsim/ForeignSimulatorEngine.java
- eventsim/src/test/groovy/com/intel/dai/eventsim/DataLoaderSpec.groovy
- eventsim/src/test/groovy/com/intel/dai/eventsim/ForeignSimulatorEngineSpec.groovy
> [FIX] lctn must be used to get hostname instaed of xname

- configurations/common/RasEventMetaData.json
- dai_core/src/main/java/com/intel/dai/AdapterOnlineTierVolt.java
- dai_core/src/test/groovy/com/intel/dai/AdapterDaiMgrSpec.groovy
- data/db/DAI-Volt-Procedures.sql
- populate_schema/src/test/java/com/intel/dai/populate/OnlineTierDataLoaderTest.java
- procedures/src/main/java/com/intel/dai/procedures/ReservationUpdated.java
> [Merge] Updated common code merge.

- dai_core/src/main/java/com/intel/dai/DataMoverAmqp.java
> [Fix] Prevent missing RMQ from stopping the DAI Manager shutdown.

- build.gradle
> [Fix] New VoltDB YAML files without population.

- .github/workflows/main.yml
- .github/workflows/pytest.yml
> [Try] Replacing Travis-CI with github workflows.

- .github/workflows/main.yml
- .github/workflows/pytest.yml
> [Test] Testing workflows.

- configurations/eventsim/ProviderProvisionerNetworkForeignBus.json
- provisioners/src/main/java/com/intel/dai/provisioners/NetworkListenerProviderForeignBus.java
- provisioners/src/test/java/com/intel/dai/provisioners/NetworkListenerProviderForeignBusTest.java
- provisioners/src/test/resources/resources/data-samples/sample-config.json
- provisioners/src/test/resources/resources/data-samples/sample4.json
- provisioners/src/test/resources/resources/data-samples/sample5.json
- runtime_utils/src/main/java/com/intel/runtime_utils/TimeUtils.java
> [FEAT] parsing timestamp data from string in console messages

- dai_core/src/main/java/com/intel/dai/DataReceiverAmqp.java
> [Fix] NearlineTier hanging on shutdown with missing RabbitMQ.

- configurations/aurora/MachineConfig.json
- configurations/aurora/NearlineConfig.json
- configurations/aurora/ProviderMonitoringNetworkForeignBus.json
- configurations/aurora/ProviderProvisionerNetworkForeignBus.json
- configurations/aurora/SystemManifest.json
- configurations/aurora/volt.ip
Updates to the aurora configuration to work with a sample HPCM cluster
> Sample HPCM cluster configuration

- dai_core/src/main/java/com/intel/dai/dsapi/HWInvDbApi.java
- dai_core/src/main/java/com/intel/dai/dsapi/pojo/FruHost.java
- dai_core/src/main/java/com/intel/dai/dsimpl/voltdb/VoltHWInvDbApi.java
- inventory/src/integration/groovy/com/intel/dai/inventory/api/es/ElasticsearchITSpec.groovy
- inventory/src/integration/resources/scripts/inventory.sql
- inventory/src/integration/resources/scripts/start-voltdb.sh
> First component tests for new inventory.

- build.gradle
- dai_core/src/main/java/com/intel/dai/dsapi/HWInvDbApi.java
- dai_core/src/main/java/com/intel/dai/dsimpl/voltdb/VoltHWInvDbApi.java
- inventory/src/main/java/com/intel/dai/inventory/api/es/ElasticsearchIndexIngester.java
- inventory/src/main/java/com/intel/dai/inventory/api/es/NodeInventoryIngestor.java
> Refactored all voltdb operations from inventory into dai_core.

- components.pipeline.groovy
- dai_core/src/integration/groovy/com/intel/dai/dsimpl/voltdb/VoltHWInvDbApiITSpec.groovy
- dai_core/src/main/java/com/intel/dai/Adapter.java
- dai_core/src/main/java/com/intel/dai/AdapterOnlineTier.java
- dai_core/src/main/java/com/intel/dai/NearlineTableUpdater.java
- dai_core/src/main/java/com/intel/dai/dsapi/HWInvDbApi.java
- dai_core/src/main/java/com/intel/dai/dsimpl/jdbc/DataLoaderApiJdbc.java
- dai_core/src/main/java/com/intel/dai/dsimpl/voltdb/VoltHWInvDbApi.java
- dai_core/src/test/java/com/intel/dai/AdapterOnlineTierTest.java
- data/db/Combined_VoltDB.sql
- data/db/DAI-Tier2-Schema-Psql.sql
- inventory/src/integration/groovy/com/intel/dai/inventory/InventoryUpdateThreadITSpec.groovy
- inventory/src/integration/groovy/com/intel/dai/inventory/api/es/ElasticsearchITSpec.groovy
- inventory/src/integration/groovy/com/intel/dai/inventory/api/es/IndexIngestersITSpec.groovy
- inventory/src/integration/resources/scripts/drop_inventory_data.sh
- inventory/src/integration/resources/scripts/inventory.sql
- inventory/src/integration/resources/scripts/postgres_inventory.sql
- inventory/src/integration/resources/scripts/restart_voltdb.sh
- inventory/src/integration/resources/scripts/setup_testbed.sh
- inventory/src/integration/resources/scripts/teardown_testbed.sh
- inventory/src/main/java/com/intel/dai/inventory/InventoryUpdateThread.java
- inventory/src/main/java/com/intel/dai/inventory/api/es/Elasticsearch.java
- inventory/src/main/java/com/intel/dai/inventory/api/es/ElasticsearchIndexIngester.java
- inventory/src/main/java/com/intel/dai/inventory/api/es/NodeInventoryIngester.java
- procedures/src/main/java/com/intel/dai/procedures/DataMoverGetListOfRecsToMove.java
- sandbox_pipelines/sandbox.components.pipeline.groovy
> Initial loading completed; datamover done.

- dai_core/src/main/java/com/intel/dai/dsapi/InventorySnapshot.java
- dai_core/src/main/java/com/intel/dai/dsimpl/jdbc/InventorySnapshotJdbc.java
- inventory/src/main/java/com/intel/dai/inventory/api/es/NodeInventoryIngester.java
> Extracted values to be used for ingestion into PO tables.

- build.gradle
- dai_core/src/integration/groovy/com/intel/dai/dsimpl/jdbc/InventorySnapshotJdbcITSpec.groovy
- dai_core/src/integration/groovy/com/intel/dai/dsimpl/voltdb/VoltHWInvDbApiITSpec.groovy
- dai_core/src/main/java/com/intel/dai/dsapi/InventorySnapshot.java
- dai_core/src/main/java/com/intel/dai/dsimpl/jdbc/InventorySnapshotJdbc.java
- inventory/src/integration/groovy/com/intel/dai/inventory/InventoryUpdateThreadITSpec.groovy
- inventory/src/integration/groovy/com/intel/dai/inventory/api/es/IndexIngestersITSpec.groovy
- inventory/src/integration/resources/scripts/docker-compose/db.yml
- inventory/src/integration/resources/scripts/restart_voltdb.sh
- inventory/src/main/java/com/intel/dai/inventory/InventoryUpdateThread.java
- inventory/src/main/java/com/intel/dai/inventory/api/es/NodeInventoryIngester.java
> Added postgres test server to component tests.

- configurations/aurora/ProviderProvisionerNetworkForeignBus.json
- configurations/eventsim/ProviderProvisionerNetworkForeignBus.json
- provisioners/src/main/java/com/intel/dai/provisioners/NetworkListenerProviderForeignBus.java
- provisioners/src/test/java/com/intel/dai/provisioners/NetworkListenerProviderForeignBusTest.java
- provisioners/src/test/resources/resources/data-samples/sample-config.json
- provisioners/src/test/resources/resources/data-samples/sample1.json
- provisioners/src/test/resources/resources/data-samples/sample5.json
- provisioners/src/test/resources/resources/data-samples/sample6.json
- provisioners/src/test/resources/resources/data-samples/sample7.json
> [FEAT] parse new data format for power and heartbeat message

- configurations/common/RasEventMetaData.json
> [Merge] New changes to RasEventMetadata.

- components.pipeline.groovy
> Added missing credential to component level test.

- configurations/aurora/ProviderProvisionerNetworkForeignBus.json
- configurations/eventsim/ProviderProvisionerNetworkForeignBus.json
> [FIX] remove obsolete url info in config files

- configurations/aurora/ProviderMonitoringNetworkForeignBus.json
- monitoring/src/main/java/com/intel/dai/monitoring/RasEventProviderHPCM.java
- monitoring/src/main/java/com/intel/dai/monitoring/TopicEventSyslog.java
- monitoring/src/test/groovy/com/intel/dai/monitoring/TopicEventSyslogSpec.groovy
> [FEAT] data parse store and monitor syslog data

- configurations/aurora/ProviderMonitoringNetworkForeignBus.json
- configurations/common/RasEventMetaData.json
- monitoring/src/main/java/com/intel/dai/monitoring/EnvironmentalProviderHPCM.java
- monitoring/src/main/java/com/intel/dai/monitoring/TopicMetricFabricCritTelemetry.java
- monitoring/src/main/java/com/intel/dai/monitoring/TopicMetricFabricPerfTelemetry.java
- monitoring/src/test/groovy/com/intel/dai/monitoring/TopicMetricFabricCritTelemetrySpec.groovy
- monitoring/src/test/groovy/com/intel/dai/monitoring/TopicMetricFabricPerfTelemetrySpec.groovy
> [FEAT] parse and store fabric crit and perf data

- configurations/aurora/MachineConfig_Australis.json
- configurations/aurora/SystemManifest_Australis.json
- configurations/hw2/MachineConfig_Australis.json
- configurations/hw2/SystemManifest_Australis.json
Signed-off-by: Naian Sai <naian.sai@intel.com>
> Adding Australis config files to aurora and hw2

- build.gradle
- configurations/aurora/health_check.json
- configurations/eventsim/health_check.json
- scripts/health_check
> Added Health Check that installed DAI/DS is healthy

- configurations/aurora/scripts/Aurora.yml
> [Fix] Added another pattern for fabric switches.

- build.gradle
> [Fix] for tests failing.

- configurations/common/RasEventMetaData.json
- monitoring/src/main/java/com/intel/dai/monitoring/RasEventProviderHPCM.java
- monitoring/src/main/java/com/intel/dai/monitoring/TopicEventFabricHealthTelemetry.java
- monitoring/src/test/groovy/com/intel/dai/monitoring/TopicEventFabricHealthTelemetrySpec.groovy
> [FEAT] fabricHealthTelemetry ras event monitoring

- provisioners/src/main/java/com/intel/dai/provisioners/NetworkListenerProviderForeignBus.java
- provisioners/src/test/resources/resources/data-samples/sample6.json
- provisioners/src/test/resources/resources/data-samples/sample7.json
> [FEAT] adding timestamp value to heartbeat message
